### ISSUE TITLE
🚀 Feature: 希望大佬可以适配智谱清言智能体

### ISSUE THREAD

**Issue by poblm** [Ikaros-521/AI-Vtuber#1013]
### 希望能解决的问题

求加功能

### 描述所需要的功能

chatglm.cn智谱清言智能体很好用，我用来做文档知识库的回答，感觉比讯飞那个理解能力更好更智能和不容易出错，希望大佬能加进去，现在的智谱ai不能用那个智能体的api key

**Comment by Ikaros-521** [comment]
虽然但是 智能体没有提供api

**Comment by poblm** [comment]
![智能体api](https://github.com/user-attachments/assets/2d145598-23ef-42d6-9b56-5561d68bcdcb)
好像是有api的
还有大佬能不能把ai返回的内容输入到抖音直播后台作为弹幕发送出去？有时候我不需要语音回复，只想作为一个ai小助手在公屏回复，现在这个功能全网找了很久都没有，感谢回复

**Comment by Ikaros-521** [comment]
> ![智能体api](https://private-user-images.githubusercontent.com/21242040/375173218-2d145598-23ef-42d6-9b56-5561d68bcdcb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjI4MjYsIm5iZiI6MTcyODUyMjUyNiwicGF0aCI6Ii8yMTI0MjA0MC8zNzUxNzMyMTgtMmQxNDU1OTgtMjNlZi00MmQ2LTliNTYtNTU2MWQ2OGJjZGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAxMDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOTM0OGNlNWMzNmM2N2YxOGY2ZjdkNzdlM2Q4MWRjN2ViODU5ZmY5YmY0YjgxMThhNDY0NTEzYmZiYjcyZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L67SdSd8IBIjpYnSIFmp4hb-eNKEhIt_qt3Snkg7NJc) 好像是有api的 还有大佬能不能把ai返回的内容输入到抖音直播后台作为弹幕发送出去？有时候我不需要语音回复，只想作为一个ai小助手在公屏回复，现在这个功能全网找了很久都没有，感谢回复

让我看看，评论区返回找不到方案

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/1015
