### ISSUE TITLE
🐛 Bug: WebSocket error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007) WebSocket connection closed.

### ISSUE THREAD

**Issue by Valariedd** [Ikaros-521/AI-Vtuber#1017]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20240510

### 描述问题

调试抖音直播间时，报证书错误 WebSocket error:  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)
WebSocket connection closed.

### 复现步骤

 WebSocket error:  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)
WebSocket connection closed.

### 期望的结果

 WebSocket error:  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)
WebSocket connection closed.

### 截图或日志

 WebSocket error:  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)
WebSocket connection closed.

**Comment by Ikaros-521** [comment]
ws没走ssl的，另外版本有点低了。

**Comment by Ikaros-521** [comment]
edge-tts 更新到6.1.15 还能凑合用
