### ISSUE TITLE
🐛 Bug: Edge-TTS 403错误：WSServerHandshakeError: 403, message='Invalid response status',

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#1021]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

main

### 描述问题

```
  File "E:\GitHub_pro\AI-Vtuber\utils\audio_handle\my_tts.py", line 348, in edge_tts_api
    await communicate.save(voice_tmp_path)
  File "E:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\edge_tts\communicate.py", line 492, in save
    async for message in self.stream():
  File "E:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\edge_tts\communicate.py", line 388, in stream
    async with aiohttp.ClientSession(
  File "E:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
  File "E:\GitHub_pro\AI-Vtuber\Miniconda3\lib\site-packages\aiohttp\client.py", line 821, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://speech.platform.bing.com/consumer/speech/synthesize/readaloud/edge/v1?TrustedClientToken=11&ConnectionId=11')
```

### 复现步骤

直接启动复现

**Comment by Moemu** [comment]
如果想要继续使用Edge-TTS的话，只能走代理了。还是考虑别的TTS方案吧
https://github.com/rany2/edge-tts/issues/265

**Comment by Ikaros-521** [comment]
> 如果想要继续使用Edge-TTS的话，只能走代理了。还是考虑别的TTS方案吧 [rany2/edge-tts#265](https://github.com/rany2/edge-tts/issues/265)

pip install edge-tts==6.1.13 -i https://pypi.org/simple

吃枣药丸 绷不住了

**Comment by Moemu** [comment]
彻底解决问题的方法：

https://github.com/Ikaros-521/AI-Vtuber/blob/3b64b69467c1e8791befc52ea3ddf4a4eb9a3bba/utils/audio_handle/my_tts.py#L347

加上代理：

```python
communicate = edge_tts.Communicate(text=data["content"], voice=data["voice"], rate=data["rate"], volume=data["volume"],proxy="http://127.0.0.1:xxxx")
```

**Comment by Ikaros-521** [comment]
> 彻底解决问题的方法：
> 
> https://github.com/Ikaros-521/AI-Vtuber/blob/3b64b69467c1e8791befc52ea3ddf4a4eb9a3bba/utils/audio_handle/my_tts.py#L347
> 
> 加上代理：
> 
> ```python
> communicate = edge_tts.Communicate(text=data["content"], voice=data["voice"], rate=data["rate"], volume=data["volume"],proxy="http://127.0.0.1:xxxx")
> ```

绷 对国内小白吃不消，代理是啥他们都搞不懂

**Comment by Ikaros-521** [comment]
> 彻底解决问题的方法：
> 
> https://github.com/Ikaros-521/AI-Vtuber/blob/3b64b69467c1e8791befc52ea3ddf4a4eb9a3bba/utils/audio_handle/my_tts.py#L347
> 
> 加上代理：
> 
> ```python
> communicate = edge_tts.Communicate(text=data["content"], voice=data["voice"], rate=data["rate"], volume=data["volume"],proxy="http://127.0.0.1:xxxx")
> ```

不过感谢更新，可以先加上，自选
