### ISSUE TITLE
🐛 Bug: 获取链接设备异常

### ISSUE THREAD

**Issue by irrikrlla** [Ikaros-521/AI-Vtuber#1044]
### 操作系统

Windows

### Python 版本

3.11.9

### AI Vtuber 版本

v0.29 20240418

### 描述问题

初始化时记录设备id有误（如截图所示），使得webui第6936行出现报错ValueError: Invalid value: 0；诡异的事是，

### 复现步骤

无法提供详细操作步骤，运行webui.py直接出现报错

如截图所示，

Windows设备为台式机，麦克风，摄像头为外接设备。可通过截图发现唯一为0 的设备是Microsoft 声音映射器？其他设备都不是0

### 期望的结果

期望正常弹出webui链接

### 截图或日志

![image](https://github.com/user-attachments/assets/7dfe11a9-94a8-4916-a60f-825b5ead73be)

**Comment by Ikaros-521** [comment]
nicegui版本有问题

**Comment by Ikaros-521** [comment]
> > nicegui版本有问题
> 
> 非常感谢，1.4.30在我这还是有问题，退回到了1.4.25.成功登录界面

建议参考common 的版本，可以减少问题发生的概率
