### ISSUE TITLE
🐛 Bug: 出现异常 tmp += chunk.choices[0].delta.content TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by d11gsx** [Ikaros-521/AI-Vtuber#1049]
### 操作系统

Windows

### Python 版本

python312

### AI Vtuber 版本

AI-Vtuber-20241024

### 描述问题

2024-11-02 20:19:01.753Loaded as API: http://127.0.0.1:7860/ ✔
 | ERROR    | utils.my_handle:llm_stream_handle_and_audio_synthesis:1908 - Traceback (most recent call last):
  File "D:\aizb\AI-Vtuber-20241024\utils\my_handle.py", line 1737, in llm_stream_handle_and_audio_synthesis
    tmp += chunk.choices[0].delta.content
TypeError: can only concatenate str (not "NoneType") to str
![微信截图_20241102204444](https://github.com/user-attachments/assets/c0fb6d32-a7a3-4424-abb1-75bb343b469c)

### 复现步骤

![微信截图_20241102204444](https://github.com/user-attachments/assets/6fa1b1f6-781c-44d6-af66-f4b78bc01f7e)

**Comment by Ikaros-521** [comment]
关掉流式
