### ISSUE TITLE
 警告：text_generation_webui无返回

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#1050]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20241028整合包

### 描述问题

使用text_generation_webui卻顯示錯誤如下
![螢幕擷取畫面 2024-11-02 222046](https://github.com/user-attachments/assets/9a0db98e-052f-4789-9810-119ca56529fc)

以下為配置
![螢幕擷取畫面 2024-11-02 222502](https://github.com/user-attachments/assets/d137ec31-346e-443f-9908-88494c540b4f)

用cmd運行netstat沒顯示127.0.0.1:5000

### 复现步骤

設定好後運行

**Comment by Ikaros-521** [comment]
logging 换成logger，参考其他程序写法

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/1054
