### ISSUE TITLE
无法读取webui配置到变量！

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#1056]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20241028整合包

### 描述问题

在頁面配置裡設定關閉大量板塊，重啟後就再也無法儲存任何配置

以下為報錯
2024-11-13 00:11:31.748 | ERROR    | __main__:webui_config_to_dict:3282 - 无法读取webui配置到变量！
free variable 'input_claude_slack_user_token' referenced before assignment in enclosing scope
2024-11-13 00:11:31.821 | ERROR    | __main__:webui_config_to_dict:3284 - Traceback (most recent call last):
  File "D:\AI-Vtuber-20241028\webui.py", line 2234, in webui_config_to_dict
    "slack_user_token": (input_claude_slack_user_token, 'str'),
NameError: free variable 'input_claude_slack_user_token' referenced before assignment in enclosing scope

### 复现步骤

如問題所述

### 截图或日志

![image](https://github.com/user-attachments/assets/2513b9d2-b730-4ef5-8bab-cb82ba1d6f39)
![image](https://github.com/user-attachments/assets/71537cca-caaf-4888-8536-18a3a253f230)

**Comment by albertyu123456789** [comment]
有需要其他資訊請跟我說

**Comment by albertyu123456789** [comment]
以下是chatgpt 的回答（問了但沒看懂）

这个错误是因为变量 input_claude_slack_user_token 在赋值之前被引用了。在 Python 中，如果一个变量在本地或全局范围内没有定义，访问它会引发 NameError。

以下是解决此问题的几个步骤：

1. 检查变量初始化：确保在 webui_config_to_dict 函数中使用变量 input_claude_slack_user_token 之前，已经对其进行了定义和赋值。


2. 设置默认值：如果该变量可能没有定义，考虑在脚本的开头给它一个默认值（例如空字符串 ""）。


3. 调整变量作用域：如果 input_claude_slack_user_token 应该是全局变量，可以在函数内部声明 global input_claude_slack_user_token。但如果它是一个局部变量，请确保在引用之前对其赋值。


4. 增加错误处理：可以在引用变量的代码行前加一个异常处理（如 try-except），以捕获可能的错误。



以下是设置默认值的示例：

try:
    input_claude_slack_user_token
except NameError:
    input_claude_slack_user_token = ""

或者，确保在调用 webui_config_to_dict 函数时，传入这个变量，避免出现变量未定义或未赋值的问题。这样可以防止代码在引用变量时发生错误。

**Comment by Ikaros-521** [comment]
不得了不得了 你发现了大bug

**Comment by albertyu123456789** [comment]
怎麼說（心裡很興奮）

**Comment by albertyu123456789** [comment]
🤔我記得以前不會因為板塊關閉而出bug

**Comment by Ikaros-521** [comment]
> 🤔我記得以前不會因為板塊關閉而出bug

因为改版了

**Comment by albertyu123456789** [comment]
原來

**Comment by albertyu123456789** [comment]
是說，text generation webui能在ai vtb中切換模型嗎？

**Comment by Ikaros-521** [comment]
> 是說，text generation webui能在ai vtb中切換模型嗎？

没实现

**Comment by albertyu123456789** [comment]
所以是要先在text generation webui那邊載入模型在到ai vtb使用？

**Comment by Ikaros-521** [comment]
> 所以是要先在text generation webui那邊載入模型在到ai vtb使用？

对

**Comment by albertyu123456789** [comment]
遇到新問題

**Comment by albertyu123456789** [comment]
顯示保存成功但事實上沒有保存

**Comment by Ikaros-521** [comment]
> 顯示保存成功但事實上沒有保存，連後台也沒有顯示相較訊息

具体是哪个

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/1058  姑且先修了个

**Comment by albertyu123456789** [comment]
> > 顯示保存成功但事實上沒有保存，連後台也沒有顯示相較訊息
> 
> 具体是哪个

就是關閉火山引擎板塊

**Comment by Ikaros-521** [comment]
> > > 顯示保存成功但事實上沒有保存，連後台也沒有顯示相較訊息
> > 
> > 
> > 具体是哪个
> 
> 就是關閉火山引擎板塊

https://github.com/Ikaros-521/AI-Vtuber/pull/1059
刚好漏了
