### ISSUE TITLE
實現從webui.py中切換語言(粗糙，希望給個建議)

### ISSUE THREAD

**Issue by verdo568** [Ikaros-521/AI-Vtuber#1065]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20241028整合包

### 描述功能

於 data = LanguageManager('en')中括弧裡可透過輸入不同語言代號進行切換，改好後須重啟webui
大致長這樣

![螢幕擷取畫面 2024-11-26 210544](https://github.com/user-attachments/assets/2fa96f9d-8bc1-4dce-8da4-9d958aec1518)
....................
from language import LanguageManager
![螢幕擷取畫面 2024-11-26 210529](https://github.com/user-attachments/assets/356c1540-dcd0-4929-ab7e-bccead4d9368)
以下為例子
data.get_variable('Chat_Mode_')
![image](https://github.com/user-attachments/assets/6e9bf969-0447-4a6e-b134-0776a9e4f463)
以下為language.py
![螢幕擷取畫面 2024-11-26 210943](https://github.com/user-attachments/assets/939539d1-396e-4566-911a-245bb0e8254c)
以下為data.py(沒想好名字)
![螢幕擷取畫面 2024-11-26 210857](https://github.com/user-attachments/assets/63757303-6c84-4715-8f95-aeb717278a8d)

### 复现步骤

無

### 期望的结果

希望能夠給點建議

**Comment by albertyu123456789** [comment]
更新:已將get_variable改成get_variable_language，self.variables改成self.variables_language

**Comment by Ikaros-521** [comment]
nicegui做语言切换不好搞，加上这么多配置工作量太大，还是直接上个浏览器翻译插件 翻译一下好了。

**Comment by Ikaros-521** [comment]
或者重做整个前端 也可以，配置部分提供了 简易的接口可以设置

**Comment by albertyu123456789** [comment]
> 或者重做整个前端 也可以，配置部分提供了 简易的接口可以设置

瞭解

**Comment by albertyu123456789** [comment]
我最大的問題時下面那條我知怎麼處理
f"停止错误:{e}"

**Comment by Ikaros-521** [comment]
> 我最大的問題時下面那條我不知怎麼處理 f"停止错误:{e}"

这种自定义内容，除非统一规范命名，要么内容走到翻译中转换后输出， 不然太混乱没法去做匹配翻译
