### ISSUE TITLE
录音文件 talk.py

### ISSUE THREAD

**Issue by laomutouhz** [Ikaros-521/AI-Vtuber#113]
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/55431840/a3b1d884-ea66-411a-8276-454054ed5e0e)
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/55431840/f5620336-4b25-4ce0-90d0-cf5bf3f1b4d5)
如果选择的开始录音快捷键为字母，比如我为q，这里有一个大小写的问题，导致后续逻辑执行不到。
另外感觉本地录音模式比较实用，比如我按一个q之后，除了判断冷却时间之外，应该暂时阻塞其他按键，再按一个s可以结束录音监听，下次按q再把进程起起来。。
现模式主要是有这样一个问题，比如我调试的时候，按了f8下一步，发现循环又进来这个方法了，现在一直在监听，有点套娃
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/55431840/67d7a24f-103c-4137-8c77-e42132edc752)
以上纯属个人意见，改不改无所谓

**Comment by Ikaros-521** [comment]
大小写问题之后解决
不阻塞其他感觉做不到，其他按键触发是会进入到按键触发，但会直接return。
持续录音功能之后会做。

**Comment by Ikaros-521** [comment]
大佬 不如直接一个pr带我走吧
![E{ZMTHZO YPQ NW 5IC_Y L](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/7e570174-f46d-45f3-816e-46aafaa6c165)

**Comment by Ikaros-521** [comment]
- 聊天模式 按键触发兼容英文大小写字母。
- 聊天模式 支持循环录音功能，新增停止触发按键。
https://github.com/Ikaros-521/AI-Vtuber/pull/115
