### ISSUE TITLE
怎样连接自己部署的langchain-chatglm

### ISSUE THREAD

**Issue by liuzj288** [Ikaros-521/AI-Vtuber#214]
刚刚部署成功了，不过api跟chatglm不太一样，看起来是openai，config文件里面应该怎么填？

![image](https://github.com/Ikaros-521/AI-Vtuber/assets/13833404/b0f0e914-d7d8-4180-9426-4b45a57610f3)

**Comment by Ikaros-521** [comment]
还未接入，待办

**Comment by Ikaros-521** [comment]
有兴趣的话，可以自行开发补充功能。
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/b3ba890b-32e6-4684-abdb-3012504d9267)

**Comment by liuzj288** [comment]
> 还未接入，待办

刚更新，怎么寄了
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/13833404/683cc12b-2aef-47e6-ba04-0a851b764f3d)

**Comment by Ikaros-521** [comment]
> > 还未接入，待办
> 
> 刚更新，怎么寄了 ![image](https://user-images.githubusercontent.com/13833404/259649920-683cc12b-2aef-47e6-ba04-0a851b764f3d.png)

看着应该是科大讯飞的库有版本变更，部分不兼容了。
参考版本：
parkdesk-api           1.0.3
websocket-client        1.6.0
websocket-client-py3    0.15.0
websockets              11.0.3

**Comment by Ikaros-521** [comment]
所有库版本 可以参考 requirement common
