### ISSUE TITLE
主干分支最新code在win11下安装报错

### ISSUE THREAD

**Issue by linkerlin** [Ikaros-521/AI-Vtuber#215]
ERROR: Cannot install -r requirements_bilibili.txt (line 27), -r requirements_bilibili.txt (line 5) and aiohttp because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested aiohttp
    edge-tts 6.1.6 depends on aiohttp>=3.8.0
    bilibili-api 9.1.0 depends on aiohttp~=3.7.4.post0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

我想应该是 bilibili-api 的版本太旧？

**Comment by Ikaros-521** [comment]
文档写了解决方案，手动安装
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/56586c75-312a-4484-82cb-816f6be6b133)
