### ISSUE TITLE
🐛 一些问题。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by pzc163** [Ikaros-521/AI-Vtuber#239]
版本：v0.17.0 或者 20230815

例如：
python：3.10.11
系统：win10

使用命令pip install -r requirements_bilibili.txt 安装环境依赖时报错:
The conflict is caused by:
    The user requested aiohttp
    edge-tts 6.1.6 depends on aiohttp>=3.8.0
    bilibili-api 9.1.0 depends on aiohttp~=3.7.4.post0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

使用命令pip install -r requirements_common.txt 安装环境依赖时报错:

The conflict is caused by:
    The user requested chardet==4.0.0
    The user requested chardet==5.1.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

请问
pip install -r requirements_bilibili.txt
pip install -r requirements_dy.txt
pip install -r requirements_ks.txt
pip install -r requirements_talk.txt
这四个依赖和requirements_common.txt的关系是什么？安装顺序有要求吗？目前来看版本冲突有点多

**Comment by pzc163** [comment]
问题已经解决，需要删除requirements_bilibili.txt 文档中bilibili-api 后面的版本号，因为原作者由于参加工作的原因，已经停止更新版本，换做其他人继续接受更新，最新的版本是15.5.4 地址是:https://github.com/Nemo2011/bilibili-api.

**Comment by Ikaros-521** [comment]
> 问题已经解决，需要删除requirements_bilibili.txt 文档中bilibili-api 后面的版本号，因为原作者由于参加工作的原因，已经停止更新版本，换做其他人继续接受更新，最新的版本是15.5.4 地址是:https://github.com/Nemo2011/bilibili-api.

装的就是python版，冲突需要手动处理下，文档其实有写的
