### ISSUE TITLE
请问考虑加入WebUI么？

### ISSUE THREAD

**Issue by nijisakai** [Ikaros-521/AI-Vtuber#256]
#### 您使用的场景？ | 1. Your usage scenarios?
有性能的设备（A800）在Linux服务器上（CentOS 7）。
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
A webUI.

**Comment by Ikaros-521** [comment]
> 

写过点，不过感觉还是麻烦了点
![TUD~V_ `BTEOO`G_5PFVQSK](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/0df16890-319c-4427-92cf-bfb3b4bf9fde)

**Comment by Ikaros-521** [comment]
webui大部分功能已经实现，内测阶段
