### ISSUE TITLE
考虑把ai.ie.cx域名更换成luna-ai.ie.cx

### ISSUE THREAD

**Issue by XzaiCloud** [Ikaros-521/AI-Vtuber#305]
要不然域名太多了容易搞混（
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/98635300/a7d6bf2a-80c6-4e32-85c4-e35be95bde9f)

**Comment by XzaiCloud** [comment]
或者是luna.ie.cx，各位给点建议（

**Comment by Ikaros-521** [comment]
已替换
