### ISSUE TITLE
🙋 b站弹幕无法获取到用户全名

### ISSUE THREAD

**Issue by Ikaros-521** [Ikaros-521/AI-Vtuber#308]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
20230825

### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win11

### 预期行为 | Expected behavior
正常获取

### 实际行为 | Actual behavior
用户名：L*****

### 原因分析（如果可以） | Cause analysis (if possible)
b站接口变动

### 问题重现步骤 | Steps to reproduce the problem
直接运行复现

**Comment by Ikaros-521** [comment]
解决方案参考：https://github.com/Nemo2011/bilibili-api/issues/486

临时更改为开发版，`pip install bilibili-api-dev==16.0.1b2`

**Comment by Drelf2018** [comment]
修复这个问题的正式版已发布

```python
pip install bilibili-api-python==16.1.0
```

**Comment by Ikaros-521** [comment]
> 修复这个问题的正式版已发布
> 
> ```python
> pip install bilibili-api-python==16.1.0
> ```

感谢大佬
