### ISSUE TITLE
🐛 聊天页 ctrl+c会关闭程序问题

### ISSUE THREAD

**Issue by DoshideDK** [Ikaros-521/AI-Vtuber#309]
#### 您使用的版本？ | Your usage version?
例如：20230903

#### 您使用的python版本&系统环境？ | Your usage python version & system?
例如：
python：3.10.11
系统：win11

#### 您使用的场景？ | Your usage scenarios?
聊天页面
#### 您做了什么操作？ | What did you do?
按住CTRL+C
#### 您遇到了什么问题？ | What are your problems?
关闭gui
#### 您期望的结果是怎样的？ | What is your expected outcome?
不关闭gui

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/310  
已更新
