### ISSUE TITLE
动态文案切分问题

### ISSUE THREAD

**Issue by langyaya** [Ikaros-521/AI-Vtuber#316]
测试两天动态文案发现个问题 如果直接读文案的话切分没有问题，如果改写的话返回的是一句话一句的合成，中间明显的卡顿感

**Comment by Ikaros-521** [comment]
待分析具体原因

**Comment by Ikaros-521** [comment]
已更新 https://github.com/Ikaros-521/AI-Vtuber/commit/70f522cceda439b86599402de45b357b1a08182a
