### ISSUE TITLE
聊天页面增加快捷键

### ISSUE THREAD

**Issue by DoshideDK** [Ikaros-521/AI-Vtuber#321]
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
增加复读快捷键。增加·号（esc与tab之间的按键）为录音快捷键

**Comment by Ikaros-521** [comment]
加入待办

**Comment by Ikaros-521** [comment]
已更新 https://github.com/Ikaros-521/AI-Vtuber/pull/325

~ ` · 中文输入法下 · 的触发测试正常。
实际配置项对应的为 ` 键，位于配置项最底部
