### ISSUE TITLE
🐛 字幕打印机乱码 | [Bug] Some problem...

### ISSUE THREAD

**Issue by azcfdgbha** [Ikaros-521/AI-Vtuber#322]
#### 您使用的版本？ | Your usage version?
20230903

#### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win10

#### 您使用的场景？ | Your usage scenarios?
bilibli直播间

#### 您做了什么操作？ | What did you do?
日常直播

#### 您遇到了什么问题？ | What are your problems?
字幕打印机乱码，消失速度过快，无法调整

#### 您期望的结果是怎样的？ | What is your expected outcome?
解决部分乱码。如果能调一下字体大小或者换行，以及出现消失速度就更好了

**Comment by Ikaros-521** [comment]
可以提供下乱码是否 对应的发送的字幕日志吗？
字体大小和消失速度 没有完全开放出来是在后期计划中的。
暂时想要修改得直接修订源码

**Comment by Ikaros-521** [comment]
后续更新于 https://github.com/Ikaros-521/captions_printer

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/captions_printer/releases/tag/v0.2.0

v0.2.0
支持字体设置，支持显示隐藏参数自定义

**Comment by Ikaros-521** [comment]
乱码问题无法复现

**Comment by Ikaros-521** [comment]
> 乱码问题无法复现

据说是斜杠问题

**Comment by Ikaros-521** [comment]
还有乱码情况出现吗，具体在输出什么文本下是乱码呢
如果问题解决了，准备关issue了

**Comment by azcfdgbha** [comment]
没了，唯一出现乱码就是最小化浏览器再打开会错行，不算bug。辛苦伊卡佬了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月25日(星期三) 下午2:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ikaros-521/AI-Vtuber] 🐛 字幕打印机乱码 | [Bug] Some problem... (Issue #322)





 
还有乱码情况出现吗，具体在输出什么文本下是乱码呢
 如果问题解决了，准备关issue了

**Comment by Ikaros-521** [comment]
> 没了，唯一出现乱码就是最小化浏览器再打开会错行，不算bug。辛苦伊卡佬了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年10月25日(星期三) 下午2:17 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Ikaros-521/AI-Vtuber] 🐛 字幕打印机乱码 | [Bug] Some problem... (Issue #322) 还有乱码情况出现吗，具体在输出什么文本下是乱码呢 如果问题解决了，准备关issue了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

错行emmm 这个应该和最小化没关系，得看看

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/captions_printer/commit/21d02d7edf28764fca547b5edfb36a09b982ad32
