### ISSUE TITLE
聊天类型 本地问答问题

### ISSUE THREAD

**Issue by langyaya** [Ikaros-521/AI-Vtuber#336]
聊天类型里面可以加上 单独启动本地问答库来回答弹幕的问题吗，AI回答的有时候不靠谱

**Comment by Ikaros-521** [comment]
加入待办

**Comment by Ikaros-521** [comment]
聊天类型：不启用 应该就可以
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/7cee548f-b170-480d-b6ea-24735c6a5907)
