### ISSUE TITLE
🙋 1.智谱AI弹幕斜杠产生的乱码。 2.违禁词不能提前触达导致的生成内容和弹幕朗读（以及恶意关闭） 3.本地库的模糊调用效果不佳，且弹幕姬与读弹无生成。 4.问题前预输入文字是否可更改为能及时调整或批次输入。

### ISSUE THREAD

**Issue by azcfdgbha** [Ikaros-521/AI-Vtuber#342]
## Question Report

- 搜索打开和关闭的 [GitHub 问题](https://github.com/eryajf/go-ldap-admin/issues)

请在提交问题之前回答这些问题，谢谢。 | Please answer these questions before submitting them. Thank you.

### 你使用了哪个版本？ | Which version did you use?
20230903

### 您使用的python版本&系统环境？ | Your usage python version & system?
例如：
python：3.10.16
系统：win10

### 预期行为 | Expected behavior
稳定运行

### 实际行为 | Actual behavior
1.智谱AI弹幕斜杠产生的乱码。
2.违禁词不能提前触达导致的生成内容和弹幕朗读（以及恶意关闭）
3.本地库的模糊调用效果不佳，且弹幕姬与读弹无生成。
4.问题前预输入文字是否可更改为能及时调整或批次输入。

### 原因分析（如果可以） | Cause analysis (if possible)
1.智谱家的脑贪传递导致的，这边已经反馈给他们的工作人员但是收效甚微，烦请给个过滤。
2.违禁词只在朗读回复时触发，问题会直接念出来，建议更改为问题+答案检索或直接屏蔽问题，不然读出来不回复怪尴尬的，还能被关闭指令直接给llm关了。
3.本地库的参数不太能做到类似问题触发，相关问题也送不到LLM里面，所以建议参考随机生成的方式先预输入进llm，说不定效果会比较好（对于一些喜欢胡扯但是有文档记忆的llm有奇效）。综上，如果懒得搞建议做个空白的对api输入的调教窗口，这玩意儿比预输入估计要强上不少还省事儿，啥玩意儿都能往里扔。
4.请参考3提出的相关建议或做个可及时更改的。

**Comment by Ikaros-521** [comment]
1.https://github.com/Ikaros-521/AI-Vtuber/commit/654c4a20656b5a678a87aea02c5d3781e8b03f5d （待验证）
2.https://github.com/Ikaros-521/AI-Vtuber/commit/8e8c8da3d781e205881939c3a65e96eaf392e74f （恶意关闭问题待细化问题点）
3. https://github.com/Ikaros-521/AI-Vtuber/commit/8e8c8da3d781e205881939c3a65e96eaf392e74f（问答库匹配本身就是模糊命中，换llm做这效果，建议直接关掉本地问答库功能，直接在llm实现；单独的调教页倒是可以考虑看看）
4. 实时调整配置项确实有点麻烦，虽然可以每次重新读取config配置，但会涉及到保存问题。预估在webui版本中有所优化

**Comment by Ikaros-521** [comment]
智谱回复内容过滤：https://github.com/Ikaros-521/AI-Vtuber/pull/365

**Comment by Ikaros-521** [comment]
无TTS合成的LLM调教形式，排入开发计划
