### ISSUE TITLE
🚀 关于智谱characterglm调用实现的请求

### ISSUE THREAD

**Issue by azcfdgbha** [Ikaros-521/AI-Vtuber#345]
#### 你使用了哪个版本？ | Which version did you use?
20230903

#### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.16
系统：win10

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
智谱新出了个可以拟人针对角色扮演的接口，请求尝试实现，详情网址如下：
https://open.bigmodel.cn/dev/api#characterglm

**Comment by Ikaros-521** [comment]
基本功能已经实现：https://github.com/Ikaros-521/AI-Vtuber/pull/346
GUI未适配

**Comment by Ikaros-521** [comment]
GUI已适配：https://github.com/Ikaros-521/AI-Vtuber/pull/347

**Comment by azcfdgbha** [comment]
牛批

**Comment by Ikaros-521** [comment]
![N24NL(JSDE3$}A1G6~9ZQ~J](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/3b073590-c752-4963-8c34-8923ca293aac)
