### ISSUE TITLE
使用文案页合成音频时报错，但聊天页可正常合成音频

### ISSUE THREAD

**Issue by cj0596** [Ikaros-521/AI-Vtuber#400]
使用文案页合成音频时报错，但聊天页可正常合成音频

#### 您使用的版本？ | Your usage version?
例如：20231015

#### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win11

#### 您使用的场景？ | Your usage scenarios?
使用文案页合成音频

#### 您做了什么操作？ | What did you do?
单机模式下连接 Bert-Vits2 模型，聊天页合成音频正常

#### 您遇到了什么问题？ | What are your problems?
点击合成音频报错合成失败，请查看原因“”

#### 您期望的结果是怎样的？ | What is your expected outcome?
文案页可正常合成音频
![屏幕截图 2023-11-06 001833](https://github.com/Ikaros-521/AI-Vtuber/assets/16449708/2f33b390-f9bc-49e3-a26e-739bc7ce2a58)

**Comment by Ikaros-521** [comment]
文案音频的合成并没有兼容所有的tts，bert估计没做兼容

**Comment by Ikaros-521** [comment]
应该是这个问题，已经更新 https://github.com/Ikaros-521/AI-Vtuber/pull/404

**Comment by Ikaros-521** [comment]
看看你tts的配置，这个type怎么会错呢，这个type我记得是下拉选择框呀
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/ccfe4dc7-8fe6-4381-aa4e-e16ef1306fff)

**Comment by Ikaros-521** [comment]
ok 回头我看看，那就问题不简单了

**Comment by Ikaros-521** [comment]
不过其实我是不建议使用内置的进行文案合成的，还是外面单独合成后，把音频合并下比较好。
内置的这块合成 之后也是准备拆一个单独的项目出来重新优化下

**Comment by Ikaros-521** [comment]
暂时还是能修一修的（）

**Comment by Ikaros-521** [comment]
已修复 https://github.com/Ikaros-521/AI-Vtuber/pull/413

**Comment by Ikaros-521** [comment]
文案合成 单独项目，已排入开发计划
