### ISSUE TITLE
🐛智谱ai设定在webui上无法保存更改

### ISSUE THREAD

**Issue by Cyuuri** [Ikaros-521/AI-Vtuber#463]
#### 您使用的版本？ | Your usage version?
20231108

#### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10.11
系统：win11

#### 您遇到了什么问题？ | What are your problems?
智谱ai设定在webui上无法保存更改

**Comment by Ikaros-521** [comment]
已修复 https://github.com/Ikaros-521/AI-Vtuber/pull/465
