### ISSUE TITLE
🐛 一些问题。。。 | [Bug] 无法写入配置文件！ 'alice'

### ISSUE THREAD

**Issue by aoecal** [Ikaros-521/AI-Vtuber#600]
#### 您使用的版本？ | Your usage version?
20240125

#### 您使用的python版本&系统环境？ | Your usage python version & system?

python(anaconda)：3.11.5
系统：win11

#### 您使用的场景？ | Your usage scenarios?
在WebUI里点击'保存配置'

#### 您做了什么操作？ | What did you do?
点击'保存配置'

#### 您遇到了什么问题？ | What are your problems?
系统提示: 无法写入配置文件！ 'alice'
命令行提示 : 
2024-01-29 07:46:01 - \AI-Vtuber-20240125\webui.py[line:1385] - ERROR: 无法写入配置文件！
'alice'
2024-01-29 07:46:01 - \AI-Vtuber-20240125\webui.py[line:1387] - ERROR: Traceback (most recent call last):
  File "\AI-Vtuber-20240125\webui.py", line 949, in save_config
    config_data["alice"]["api_ip_port"] = input_alice_api_ip_port.value
KeyError: 'alice'

#### 您期望的结果是怎样的？ | What is your expected outcome?
希望处理,或告知操作

**Comment by Ikaros-521** [comment]
> #### 您使用的版本？ | Your usage version?
> 20240125
> 
> #### 您使用的python版本&系统环境？ | Your usage python version & system?
> python(anaconda)：3.11.5 系统：win11
> 
> #### 您使用的场景？ | Your usage scenarios?
> 在WebUI里点击'保存配置'
> 
> #### 您做了什么操作？ | What did you do?
> 点击'保存配置'
> 
> #### 您遇到了什么问题？ | What are your problems?
> 系统提示: 无法写入配置文件！ 'alice' 命令行提示 : 2024-01-29 07:46:01 - \AI-Vtuber-20240125\webui.py[line:1385] - ERROR: 无法写入配置文件！ 'alice' 2024-01-29 07:46:01 - \AI-Vtuber-20240125\webui.py[line:1387] - ERROR: Traceback (most recent call last): File "\AI-Vtuber-20240125\webui.py", line 949, in save_config config_data["alice"]["api_ip_port"] = input_alice_api_ip_port.value KeyError: 'alice'
> 
> #### 您期望的结果是怎样的？ | What is your expected outcome?
> 希望处理,或告知操作

更新源码
