### ISSUE TITLE
🙋 问题交流 不应该局限在几个选择上

### ISSUE THREAD

**Issue by 2catycm** [Ikaros-521/AI-Vtuber#605]
应该提供通用的web接口，让用户自己去实现。
比如xuniren这个接口，不需要局限只能对接xuniren。
完全可以把AI-VTuber当做一个中间通信规范，
然后支持任意其他的虚拟身体软件，只要实现对应的web接口

**Comment by Ikaros-521** [comment]
> 应该提供通用的web接口，让用户自己去实现。 比如xuniren这个接口，不需要局限只能对接xuniren。 完全可以把AI-VTuber当做一个中间通信规范， 然后支持任意其他的虚拟身体软件，只要实现对应的web接口

本身就没啥局限，要接别的 开发就行了。
本来协议就是不同的，也没法随便对接用
