### ISSUE TITLE
🚀 回答弹幕问题时，可以将用户名作为内容的一部分

### ISSUE THREAD

**Issue by zhuangbayirou** [Ikaros-521/AI-Vtuber#646]
#### 您使用的场景？ | 1. Your usage scenarios?
B站的Ai直播

#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
1. 系统在回答弹幕问题时，可以将用户名作为内容的一部分，来进行回复，如：
   用户小明发送：伊卡洛斯，你喜欢吃青椒吗？
   系统按照“小明说：伊卡洛斯，你喜欢吃青椒吗？”来理解并回复
   
2. 该功能有自己的开关

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/652
