### ISSUE TITLE
🙋 闲时任务处理逻辑

### ISSUE THREAD

**Issue by molihuan** [Ikaros-521/AI-Vtuber#656]
### 你使用了哪个版本？
20240125

### 您使用的python版本&系统环境？
python：3.10.11
系统：win10
整合包
音频播放：pygame

### 描述

闲时任务是播放音频，如果音频很长，一旦开始播放就无法自动中断。此时有人发弹幕，弹幕无法被立即处理，必须等到闲时任务音频播放完。

我认为闲时任务的优先级应该最低，当有人发弹幕时应该立即中断闲时任务（中断音频播放），优先处理其他的任务。

参考解决方案：设置一个全局变量保存当前播放的音频路径，在播放音频时进行赋值，在处理弹幕任务时判断当前播放的音频路径是否为闲时任务设置的音频路径，如果是则停止音频播放。

**Comment by Ikaros-521** [comment]
> ### 你使用了哪个版本？
> 20240125
> 
> ### 您使用的python版本&系统环境？
> python：3.10.11 系统：win10 整合包 音频播放：pygame
> 
> ### 描述
> 闲时任务是播放音频，如果音频很长，一旦开始播放就无法自动中断。此时有人发弹幕，弹幕无法被立即处理，必须等到闲时任务音频播放完。
> 
> 我认为闲时任务的优先级应该最低，当有人发弹幕时应该立即中断闲时任务（中断音频播放），优先处理其他的任务。
> 
> 参考解决方案：设置一个全局变量保存当前播放的音频路径，在播放音频时进行赋值，在处理弹幕任务时判断当前播放的音频路径是否为闲时任务设置的音频路径，如果是则停止音频播放。

可以在audio.py进行开发，期待pr

**Comment by Ikaros-521** [comment]
配合 https://github.com/Ikaros-521/audio_player 自定义数据播放优先级
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/6745777c-3750-4823-9f66-667981d0f989)

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/753
