### ISSUE TITLE
如果想要適配Youtube需要提供哪些接口?

### ISSUE THREAD

**Issue by Arcelibs** [Ikaros-521/AI-Vtuber#66]

**Comment by Ikaros-521** [comment]
油管的弹幕捕获就可以了

**Comment by HildaM** [comment]
> 油管的弹幕捕获就可以了

油管直播应该可以开放更多限制，比国内直播平台玩得开一点

**Comment by Ikaros-521** [comment]
> > 油管的弹幕捕获就可以了
> 
> 油管直播应该可以开放更多限制，比国内直播平台玩得开一点

放荡不羁（）
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/e1a7c7ad-b010-4bf0-b895-a65ba5ddadcd)

**Comment by Arcelibs** [comment]
> 油管的弹幕捕获就可以了

找到了一個Youtube live讀取聊天室留言的
https://github.com/dghkd/KomeTube

不曉得能不能把那些留言讀取出來餵給AI

**Comment by Ikaros-521** [comment]
好家伙，喂给AI 那肯定是可以喂的，但是效果好不好那就是另一回事了0.0

**Comment by Arcelibs** [comment]
> 好家伙，喂给AI 那肯定是可以喂的，但是效果好不好那就是另一回事了0.0

行吧，大老有空能不能做個支援，我先點個star

**Comment by Ikaros-521** [comment]
> > 好家伙，喂给AI 那肯定是可以喂的，但是效果好不好那就是另一回事了0.0
> 
> 行吧，大老有空能不能做個支援，我先點個star

模型训练我也不熟
![(U}6}N~MZ5@LPK) I42TO D](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/b61985e0-ae15-4a59-9cb4-20bcc127ddb6)

**Comment by Ikaros-521** [comment]
已接入youtube
