### ISSUE TITLE
🚀 按键映射扩展功能请求（礼物触发播放指定音频）

### ISSUE THREAD

**Issue by yuffiesakiya** [Ikaros-521/AI-Vtuber#669]
能否在现有礼物触发按键映射的基础上，追加一个礼物触发预先录制好的指定音频（或触发tts指定文本）的功能？
感谢伊卡大佬！

**Comment by Ikaros-521** [comment]
功能可行，有空的时候再推进

**Comment by Ikaros-521** [comment]
礼物触发指定文本的已经实现了
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/91ada28f-1098-4a16-be69-5b0be4c5f8a7)
