### ISSUE TITLE
[解决方案]关于运行ChatGLM3整合包时遇到的报错

### ISSUE THREAD

**Issue by fires610** [Ikaros-521/AI-Vtuber#687]
整合包地址（源自luna ai）
python版本&系统环境
python：3.12
系统：win11
在运行webui.bat时出现报错
报错内容：
  File "G:\chatglm3\chatglm3\web_demo.py", line 89, in <module>
    user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style(
AttributeError: 'Textbox' object has no attribute 'style'.
解决方法：
将第89行改成：user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10)
改掉之后项目运行正常，目测无问题

**Comment by Ikaros-521** [comment]
> 整合包地址（源自luna ai） python版本&系统环境 python：3.12 系统：win11 在运行webui.bat时出现报错 报错内容： File "G:\chatglm3\chatglm3\web_demo.py", line 89, in user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style( AttributeError: 'Textbox' object has no attribute 'style'. 解决方法： 将第89行改成：user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10) 改掉之后项目运行正常，目测无问题

glm3的报错为什么在我这提issue。。。
