### ISSUE TITLE
win环境安装gemini 的pysam的问题

### ISSUE THREAD

**Issue by sssssssssh** [Ikaros-521/AI-Vtuber#735]
python：3.10.11
系统：win11

启动项目显示报错
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/54253683/5927041e-b593-4890-814b-52ecef254e7e)

然后我安装gemini显示需要安装pysam
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/54253683/d90868de-3c7c-469f-bb97-0cbb1e588e1e)

，win系统安装显示报错
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/54253683/14b2303d-947a-4be5-95d3-82476db59ce3)

**Comment by Ikaros-521** [comment]
别瞎装
