### ISSUE TITLE
🐛 PyGetWindow不支持linux

### ISSUE THREAD

**Issue by chenwei39094342** [Ikaros-521/AI-Vtuber#745]
#### 您使用的版本？ | Your usage version?
例如：最新

#### 您使用的python版本&系统环境？ | Your usage python version & system?
例如：
python：3.10.14
系统：centos stream

#### 您做了什么操作？ | What did you do?
python webui.py

#### 您遇到了什么问题？ | What are your problems?
PyGetWindow不支持linux
#### 您期望的结果是怎样的？ | What is your expected outcome?
有什么替换方案

**Comment by Ikaros-521** [comment]
注释相关代码

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/746
