### ISSUE TITLE
openai_tts好像有点问题

### ISSUE THREAD

**Issue by laojiuu** [Ikaros-521/AI-Vtuber#766]
请作者看一下openai_tts是不是有点问题，一直出错

**Comment by Ikaros-521** [comment]
测了下，没问题，是不是api密钥有问题

**Comment by laojiuu** [comment]
使用的第三方中专api，key和api是用第三方的吗？

**Comment by Ikaros-521** [comment]
> 使用的第三方中专api，key和api是用第三方的吗？

对，不过不确定第三方兼容性，得单独拉出来测一测

**Comment by laojiuu** [comment]
请问有测试tts的平台吗？我始终在AI-Vtuber上测不通

**Comment by Ikaros-521** [comment]
> 请问有测试tts的平台吗？我始终在AI-Vtuber上测不通

https://github.com/Ikaros-521/AI-Vtuber/tree/main/tests 
直接跑测试代码，话说你不是加群了吗，为什么不群里说

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/804
