### ISSUE TITLE
🐛 点歌停止命令无效，版本20240417。。。 | [Bug] Some problem...

### ISSUE THREAD

**Issue by 1982linlin** [Ikaros-521/AI-Vtuber#787]
#### 您使用的版本？ | Your usage version?
例如：main 或者 20230806

#### 您使用的python版本&系统环境？ | Your usage python version & system?
例如：
python：3.10.11
系统：win11

#### 您使用的场景？ | Your usage scenarios?
点歌
#### 您做了什么操作？ | What did you do?
停止点歌
#### 您遇到了什么问题？ | What are your problems?
停止命令无效
#### 您期望的结果是怎样的？ | What is your expected outcome?
修复bug

**Comment by Ikaros-521** [comment]
没有问题， 点歌功能的取消点歌并非是单独取消歌曲，而是取消当前播放的音频

**Comment by Ikaros-521** [comment]
这块后期是准备做优化的
