### ISSUE TITLE
🐛 抖音感谢礼物gift_num错误 | [Bug] DouYin, Gift problem...

### ISSUE THREAD

**Issue by asoefsh** [Ikaros-521/AI-Vtuber#815]
#### 您使用的版本？ | Your usage version?
2024.04.17

#### 您使用的python版本&系统环境？ | Your usage python version & system?
python：3.10
系统：win10

#### 您使用的场景？ | Your usage scenarios?
**【抖音】**平台，**【礼物答谢】**功能

#### 您做了什么操作？ | What did you do?
尝试新增除了{username}和{gift_name}以外的其他参数，例如礼物数量，单价总价。
案例：感谢{username}送的{gift_num}个单价{unit_price}元，总价{total_price}元的{gift_name}喵

#### 您遇到了什么问题？ | What are your problems?
当添加其余三个新参数时，my_handle.py会报错，如下图所示，无论是{gift_num}还是{unit_price}还是{total_price}都会报错我都尝试过了。bilibili的可以正常跑通，但我用的是抖音，出现了这个问题。从下图黄色框来看，我们是能成功接收到相关礼物参数并作为log打印出来的。
<img width="929" alt="66a27708e4d1f20fdb41d3401d1f12a" src="https://github.com/Ikaros-521/AI-Vtuber/assets/129386105/fcadd29c-793d-4799-be22-e579bf3b7305">

#### 您期望的结果是怎样的？ | What is your expected outcome?
感觉似乎是如报错所示部分的一些代码逻辑没有兼容{gift_num} {unit_price} {total_price}这三个新参数，希望能修复在【礼物答谢】以及 【按键/文案映射】这2个功能板块的上述三个参数的问题。

十分感谢！！

**Comment by Ikaros-521** [comment]
更新到最新版
