### ISSUE TITLE
WARNING: python-socketio 5.10.0 does not provide the extra 'asyncio-client'

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#850]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

2024519

### 描述问题

WARNING: python-socketio 5.10.0 does not provide the extra 'asyncio-client'

### 复现步骤

1.點安裝依賴
2.出現WARNING: python-socketio 5.10.0 does not provide the extra 'asyncio-client'就結束了

### 截图或日志

![Uploading 螢幕擷取畫面 2024-05-20 004249.png…]()

**Comment by Ikaros-521** [comment]
截图没有上传好，看不见。
req内并没有 python-socketio
不过这个库确实是在其他库中有依赖关系。
warning警告理论上来说没啥影响。估计是其他问题导致依赖安装失败。
可以从release下载旧版整合包，然后通过整合包 补充完整依赖。可以省不少功夫
