### ISSUE TITLE
使用discord來跟ai說話

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#865]
### 希望能解决的问题

無法透過discord來跟ai說話

### 描述所需要的功能

能使用discord來跟ai說話

**Comment by Ikaros-521** [comment]
呃，dc 考虑考虑。感觉没必要，接dc 直播就有点鸡肋，返回内容到dc，那不就是类似qqbot了，nonebot也有dc的适配器和插件可以用

**Comment by albertyu123456789** [comment]
我想讓朋友透過dc來和ai互動，不知道有什麼其他方法可解決？

**Comment by Ikaros-521** [comment]
互动后的数据是dc返回吗，是的话，可以看看这个 https://nonebot.dev/docs/ 
https://github.com/nonebot/nonebot2

**Comment by albertyu123456789** [comment]
感謝，我會去試試看的

**Comment by albertyu123456789** [comment]
我找到了這個 [https://github.com/ITCraftDevelopmentTeam/OneDisc] ，但他似乎要填入網址來進行連接，請問我該怎麼做

**Comment by albertyu123456789** [comment]
我表達的不夠完整，抱歉。
我的意思是dc連到ai的部分

**Comment by albertyu123456789** [comment]
了解，我知道了

**Comment by Ikaros-521** [comment]
> 了解，我知道了

祝好运
