### ISSUE TITLE
關於Windows系統安裝依賴的心得

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#868]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20240524

### 描述问题

1.開始安裝依賴前，要先將requirements.txt裡的langchain、gradio、aiohttp、bilibili-api-python、pyaudio刪除後才可以完成開始安裝，完成再手動安裝刪除的部分。
2.更新ai vtuber，要先將python 和miniconda3重新安裝（也就是解除安裝後再安裝） 後在開始照著第一點做。

我不清楚是不是只有我遇到這個問題，因為我也拿虛擬機測試過很多次了

### 复现步骤

如問題所描述

### 期望的结果

希望能得到解答

**Comment by Ikaros-521** [comment]
是的，没错。冲突部分在直接安装req的情况下得手动解决。后期补装，部分库版本向下兼容，问题不大
