### ISSUE TITLE
如何讓ai vt在yt直播時不要每一則留言回覆，例如每隔5秒之類的

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#872]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20240524

### 描述问题

如標題所示

### 复现步骤

如標題所示

**Comment by Ikaros-521** [comment]
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/47ec4972-2912-4d0a-9721-8f71cd52c5bf)

**Comment by albertyu123456789** [comment]
原來這個功能在那邊， 我知道有那個欄位，但在你解答我之前，我並不清楚他的作用是什麼

**Comment by Ikaros-521** [comment]
部分配置，鼠标悬浮有功能讲解

**Comment by albertyu123456789** [comment]
好的感謝，我會去研究看看的

**Comment by Ikaros-521** [comment]
![()_3TW8J$WO~62{ 3VROL A](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/93427d5e-5615-433d-a534-d059dc387570)

**Comment by albertyu123456789** [comment]
想問一下，數據分析中的彈幕關鍵詞統計的檔案來源是什麼，因為我想重新統計

**Comment by Ikaros-521** [comment]
数据库的弹幕表

> 想問一下，數據分析中的彈幕關鍵詞統計的檔案來源是什麼，因為我想重新統計

**Comment by albertyu123456789** [comment]
在data資料夾裡？

**Comment by Ikaros-521** [comment]
> 在data資料夾裡？
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/6f76af68-7d0e-4480-9098-b561a8774718)
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/40910637/64d634c0-e447-4dce-8185-3d54d2360cf9)

**Comment by albertyu123456789** [comment]
找到了，謝謝
