### ISSUE TITLE
Feature:连续对话，能否提供个关键词唤醒，就是只有听到关键词再开始录音分析

### ISSUE THREAD

**Issue by lhtpluto** [Ikaros-521/AI-Vtuber#874]
### 希望能解决的问题

回答或问长问题，就变成机器自己无限循环了

### 描述所需要的功能

比如只有呼唤“伊卡洛斯”时录音才启动一定时间，

进一步功能就是检测到“谢谢”、“请帮助我”等词汇时停止录音

**Comment by lhtpluto** [comment]
> ### 希望能解决的问题
> 回答或问长问题，就变成机器自己无限循环了
> 
> ### 描述所需要的功能
> 比如只有呼唤“伊卡洛斯”时录音才启动一定时间，
> 
> 进一步功能就是检测到“谢谢”、“请帮助我”等词汇时停止录音

结合数字人的对话方式，重新梳理下

**希望能解决的问题**
回答或问长问题，就变成机器自己无限循环了

**描述所需要的功能**
只有呼唤特定词汇，例如“伊卡洛斯”时，录音才启动一定时间，

LLM回复后，TTS没有朗读完前不再录音

新增停止TTS朗读按钮，解决不想听此段语音的需求；

**Comment by Ikaros-521** [comment]
播放中 及时进行录音也会混一起，当然可以让麦克风和扬声器隔离开。
具体 唤醒 中断功能，再看。
唤醒的话 倒是可以考虑做一做先

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/941
已更新

**Comment by lhtpluto** [comment]
> #941 已更新
膜拜

**Comment by Ikaros-521** [comment]
> > #941 已更新
> 膜拜

🤗
