### ISSUE TITLE
动态文案用的文心一言接口，用一会就提示报错🐛 Bug: 出现异常

### ISSUE THREAD

**Issue by olccamy** [Ikaros-521/AI-Vtuber#875]
### 操作系统

Windows

### Python 版本

一键整合包内置

### AI Vtuber 版本

最新#873

### 描述问题

动态文案用的文心一言接口，用一会就提示报错
![f5fff154aeb49bf3b33d80590383e3e7](https://github.com/Ikaros-521/AI-Vtuber/assets/86907552/a65974fb-dcfd-45d6-b29e-d883237db6b4)

### 复现步骤

动态文案用的文心一言接口，用一会就提示报错

**Comment by Ikaros-521** [comment]
改用 千帆大模型
