### ISSUE TITLE
chat_with_file.py 和 gpt.py match case 语法报错

### ISSUE THREAD

**Issue by laomutouhz** [Ikaros-521/AI-Vtuber#92]
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/55431840/58504411-37b2-4499-97c5-23fbe13d4e36)
![image](https://github.com/Ikaros-521/AI-Vtuber/assets/55431840/9056394a-8493-49a1-a6cf-047401c73161)
环境为3.10，怎么看都没有看出问题 是否考虑换一种写法

**Comment by Ikaros-521** [comment]
py3.10.11可以支持。
换语法直接 if了（）
