### ISSUE TITLE
🙋 问题交流 安装依赖时出错

### ISSUE THREAD

**Issue by ssomoss** [Ikaros-521/AI-Vtuber#945]
### 操作系统

Windows

### Python 版本

Python 3.10.10

### AI Vtuber 版本

20240418

### 描述问题

ERROR: Cannot install -r requirements.txt (line 37) and -r requirements.txt (line 70) because these package versions have conflicting dependencies.

The conflict is caused by:
    langchain 0.0.142 depends on pydantic<2 and >=1
    gradio 4.16.0 depends on pydantic>=2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

### 复现步骤

ERROR: Cannot install -r requirements.txt (line 37) and -r requirements.txt (line 70) because these package versions have conflicting dependencies.

The conflict is caused by:
    langchain 0.0.142 depends on pydantic<2 and >=1
    gradio 4.16.0 depends on pydantic>=2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Ikaros-521** [comment]
参考：https://github.com/Ikaros-521/AI-Vtuber/issues/655
或者使用 uv  https://github.com/Ikaros-521/AI-Vtuber/pull/950
