### ISSUE TITLE
🚀 Feature: ai对话过程中进行打断

### ISSUE THREAD

**Issue by Zctttt** [Ikaros-521/AI-Vtuber#959]
### 希望能解决的问题

设置终止词结束当前对话。

### 描述所需要的功能

在ai对话过程中，终止当前的回答，进行下一轮对话，就像和小爱同学说安静，有没有计划做呢？

**Comment by Ikaros-521** [comment]
暂时没有计划，只不过还在构思阶段，因为并不好做，假定在麦克风和扬声器互不干扰的情况下，倒还好，整个逻辑的实现还是有机会的，不过，并不算好方案，再看吧，什么时候心情好了，搞一个 试试好不好用

**Comment by JerryDaHeLian** [comment]
现在实现了吗？

**Comment by Ikaros-521** [comment]
> 现在实现了吗？

没

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/1037
