### ISSUE TITLE
🚀 Feature: 连续对话，提供关键词唤醒

### ISSUE THREAD

**Issue by zheng-hongkun** [Ikaros-521/AI-Vtuber#966]
### 希望能解决的问题

实时语音对话聊天功能加唤醒词。

### 描述所需要的功能

连续对话，提供关键词唤醒，只有听到关键词开头的录音，再开始录音分析（类似小爱音响或者Fay框架数字人前置词功能），否则一旦回答或问个长问题，就变成机器自己无限循环了。比如只有呼唤“伊卡洛斯”开头的录音才有效。
![屏幕截图 2024-08-12 235213](https://github.com/user-attachments/assets/f105fffb-cb06-4a28-af13-947aeab8ac88)

**Comment by zheng-hongkun** [comment]
![Uploading 屏幕截图 2024-08-12 235213.png…]()

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/941

3周前已经实现了

**Comment by Ikaros-521** [comment]
但并非每句话单独触发，而是开启后长期可以对话。单次唤醒的模式 后续考虑实现
@Ikaros-521

**Comment by zheng-hongkun** [comment]
谢谢，幸苦了，我的意思是与数字人交流沟通的时候每句话都带上前置词，因为我的应用场景必须开扬声器，如果每句话不加前置词，数字人必然就会陷入无限自问自答的场景，而且现场环境音不那么纯净，不加前置词数字人很容易对杂音响应。

**Comment by Ikaros-521** [comment]
> 谢谢，幸苦了，我的意思是与数字人交流沟通的时候每句话都带上前置词，因为我的应用场景必须开扬声器，如果每句话不加前置词，数字人必然就会陷入无限自问自答的场景，而且现场环境音不那么纯净，不加前置词数字人很容易对杂音响应。

单句携带 恩，就是这种，

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/968 已更新

**Comment by zheng-hongkun** [comment]
感谢，刚测了一下，单次唤醒还有个小小的问题，就是用前置词唤醒时，前置词没有被截掉，前置词和问题一起被传入大模型。
比如我设置前置词为“小花”，我用口令询问：“小花，今天天气怎么样。”，大模型就会回答“我没有搜索到区域为“小花”的天气情况”，这句话通过喇叭播放出来，被麦克风收声，结果又会陷入自问自答的循环。

**Comment by Ikaros-521** [comment]
> 感谢，刚测了一下，单次唤醒还有个小小的问题，就是用前置词唤醒时，前置词没有被截掉，前置词和问题一起被传入大模型。 比如我设置前置词为“小花”，我用口令询问：“小花，今天天气怎么样。”，大模型就会回答“我没有搜索到区域为“小花”的天气情况”，这句话通过喇叭播放出来，被麦克风收声，结果又会陷入自问自答的循环。

你没开 播放时不录用吗（不过如果用的metahuman-stream倒是不行）

**Comment by zheng-hongkun** [comment]
![屏幕截图 2024-08-13 222017](https://github.com/user-attachments/assets/dacd095d-ccd3-4e2d-81c6-f19e00a5626d)
选择单次唤醒是没有的。

**Comment by Ikaros-521** [comment]
> ![屏幕截图 2024-08-13 222017](https://private-user-images.githubusercontent.com/140875693/357448116-dacd095d-ccd3-4e2d-81c6-f19e00a5626d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTk4NTUsIm5iZiI6MTcyMzU1OTU1NSwicGF0aCI6Ii8xNDA4NzU2OTMvMzU3NDQ4MTE2LWRhY2QwOTVkLWNjZDMtNGUyZC04MWM2LWYxOWUwMGE1NjI2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNDMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGM1NWIyNzczMjA0OWMwNjA2NDVkMGJmNjViMjc4MjVkYThjZmU5OWQ1OWY3NzMwMDM1MjhhNzEyN2JlOGUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rwXefzO_d1pqVcEznJLpKTImOzlsvmAfRFsXVo-WtVw) 我用的metahuman-stream，选择单次唤醒是没有的。

唤醒词过滤：https://github.com/Ikaros-521/AI-Vtuber/pull/969
