### ISSUE TITLE
🐛 Bug: 环境安装问题

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#974]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20240816

### 描述问题

依照 https://github.com/Ikaros-521/AI-Vtuber/issues/868 ，也就是我幾個月前的心得安裝，結果出錯，我唯一不同的是將urllib3也刪除，因為發現2.2.2會版本衝突，希望能得到指引(解決衝突的軟體，也就是UV試過了，他會跳沒有requests這個模組)
urllib3錯誤訊息:
The conflict is caused by:
    The user requested urllib3==2.2.2
    requests 2.32.3 depends on urllib3<3 and >=1.21.1
    nicegui 1.4.30 depends on urllib3!=2.0.0, !=2.0.1, !=2.0.2, !=2.0.3, !=2.0.4, !=2.0.5, !=2.0.6, !=2.0.7, !=2.1.0, !=2.2.0, !=2.2.1 and >=1.26.18
    xingchen 1.1.5 depends on urllib3<2.1.0 and >=1.25.3

更：由於嘗試了許久都無法解決，暫時使用整合包，另外，google 翻譯似乎強制要proxy，要怎麼做才能不要用
![螢幕擷取畫面 2024-08-17 010607](https://github.com/user-attachments/assets/453fc5ab-a51f-4ac9-8f64-1fbd663e02b8)

### 复现步骤

如問題所示

**Comment by albertyu123456789** [comment]
![image](https://github.com/user-attachments/assets/7d641c64-b7c3-4eb1-a8f9-f686915bee0c)
我說的UV是這個

**Comment by Ikaros-521** [comment]
> ### 操作系统
> Windows
> 
> ### Python 版本
> 3.10.11
> 
> ### AI Vtuber 版本
> 20240816
> 
> ### 描述问题
> 依照 #868 ，也就是我幾個月前的心得安裝，結果出錯，我唯一不同的是將urllib3也刪除，因為發現2.2.2會版本衝突，希望能得到指引(解決衝突的軟體，也就是UV試過了，他會跳沒有requests這個模組) urllib3錯誤訊息: The conflict is caused by: The user requested urllib3==2.2.2 requests 2.32.3 depends on urllib3<3 and >=1.21.1 nicegui 1.4.30 depends on urllib3!=2.0.0, !=2.0.1, !=2.0.2, !=2.0.3, !=2.0.4, !=2.0.5, !=2.0.6, !=2.0.7, !=2.1.0, !=2.2.0, !=2.2.1 and >=1.26.18 xingchen 1.1.5 depends on urllib3<2.1.0 and >=1.25.3
> 
> 更：由於嘗試了許久都無法解決，暫時使用整合包，另外，google 翻譯似乎強制要proxy，要怎麼做才能不要用 ![螢幕擷取畫面 2024-08-17 010607](https://private-user-images.githubusercontent.com/154345558/358658676-453fc5ab-a51f-4ac9-8f64-1fbd663e02b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjQwMDUsIm5iZiI6MTcyNDEyMzcwNSwicGF0aCI6Ii8xNTQzNDU1NTgvMzU4NjU4Njc2LTQ1M2ZjNWFiLWE1MWYtNGFjOS04ZjY0LTFmYmQ2NjNlMDJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwMzE1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzU4Zjk3MDllZGIyZmE2NWNkNTUwMWE3YmFhZDZjNTE5Yjc2YTQ0MzRlM2E5ODlkOGYyOWY1ZjM0NjMyMTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IW1k4xJne1rElXJVD5vS8mzCZq70F3-KXwAJ6PCl4u0)
> 
> ### 复现步骤
> 如問題所示
> 
> ### 期望的结果
> _No response_
> 
> ### 截图或日志
> _No response_

谷歌肯定要开代理，不开代理那得人在国外

**Comment by Ikaros-521** [comment]
> ### 操作系统
> Windows
> 
> ### Python 版本
> 3.10.11
> 
> ### AI Vtuber 版本
> 20240816
> 
> ### 描述问题
> 依照 #868 ，也就是我幾個月前的心得安裝，結果出錯，我唯一不同的是將urllib3也刪除，因為發現2.2.2會版本衝突，希望能得到指引(解決衝突的軟體，也就是UV試過了，他會跳沒有requests這個模組) urllib3錯誤訊息: The conflict is caused by: The user requested urllib3==2.2.2 requests 2.32.3 depends on urllib3<3 and >=1.21.1 nicegui 1.4.30 depends on urllib3!=2.0.0, !=2.0.1, !=2.0.2, !=2.0.3, !=2.0.4, !=2.0.5, !=2.0.6, !=2.0.7, !=2.1.0, !=2.2.0, !=2.2.1 and >=1.26.18 xingchen 1.1.5 depends on urllib3<2.1.0 and >=1.25.3
> 
> 更：由於嘗試了許久都無法解決，暫時使用整合包，另外，google 翻譯似乎強制要proxy，要怎麼做才能不要用 ![螢幕擷取畫面 2024-08-17 010607](https://private-user-images.githubusercontent.com/154345558/358658676-453fc5ab-a51f-4ac9-8f64-1fbd663e02b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxMjQwNjAsIm5iZiI6MTcyNDEyMzc2MCwicGF0aCI6Ii8xNTQzNDU1NTgvMzU4NjU4Njc2LTQ1M2ZjNWFiLWE1MWYtNGFjOS04ZjY0LTFmYmQ2NjNlMDJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQwMzE2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNGMzMjJmN2UxZDUzY2E3ZjVkZTI0NjU2YmM5OTBjNzI5NjkwZTQxOGIwMWU3ZTQyMTgyZDYzMjg2OTQyYjhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CsiN24wYgYOyTvx5-zcxuUNyXQgMK-H5HjtsNfUPlg8)
> 
> ### 复现步骤
> 如問題所示
> 
> ### 期望的结果
> _No response_
> 
> ### 截图或日志
> _No response_

urllib3的版本冲突问题，稍微比依赖库高一点版本 可以向下兼容，问题不大

**Comment by albertyu123456789** [comment]
我人在國外，但還是行不通，llm回傳給翻譯時就報錯

**Comment by Ikaros-521** [comment]
> 我人在國外，但還是行不通，llm回傳給翻譯時就報錯

那可能我写死了走代理了，我确认一下

**Comment by albertyu123456789** [comment]
好的，感謝

**Comment by Ikaros-521** [comment]
my_translate.py 改这个试试
```
if self.config_data['google']['proxy'] != "":
    proxies = {'https': self.config_data['google']['proxy']}
else:
    proxies = None
```

**Comment by albertyu123456789** [comment]
好

**Comment by albertyu123456789** [comment]
解決了，只不過翻譯後的似乎只會用來合成tts，不會顯示在聊天紀錄裡，聊天紀錄裡依然保持原文

**Comment by albertyu123456789** [comment]
我目前能想到讓dc通話ai vtuber能監聽到的方法似乎只有用bot的方式

**Comment by Ikaros-521** [comment]
> 解決了，只不過翻譯後的似乎只會用來合成tts，不會顯示在聊天紀錄裡，聊天紀錄裡依然保持原文

那倒是没做翻译的显示

**Comment by Ikaros-521** [comment]
> 我目前能想到讓dc通話ai vtuber能監聽到的方法似乎只有用bot的方式

dc 通话 语音输入还行，bot形式的聊天接入也不是不行

**Comment by albertyu123456789** [comment]
會想用bot的原因是，我想讓我朋友通過dc跟ai vtuber聊天，就是多人的意思

**Comment by Ikaros-521** [comment]
> 會想用bot的原因是，我想讓我朋友通過dc跟ai vtuber聊天，就是多人的意思，像是在特定頻道或語音裡常駐bot

那有现成的dc bot

**Comment by albertyu123456789** [comment]
可以貼連結嗎，我找了很久都找不到

**Comment by Ikaros-521** [comment]
> 可以貼連結嗎，我找了很久都找不到

nonebot

**Comment by albertyu123456789** [comment]
好的
