### ISSUE TITLE
🐛 Bug: SiliconCloud OpenAI接口流式不兼容

### ISSUE THREAD

**Issue by geekane** [Ikaros-521/AI-Vtuber#978]
### 操作系统

Windows

### Python 版本

3.10.11

### AI Vtuber 版本

20240823

### 描述问题

我使用的是SiliconCloud的api，验证是通过的，在其他版本（0723）上也是可以在聊天页面中正常出现语音对话，但是在0823版本中却不行了，关键部分错误如下：
2024-08-23 23:13:21.829 | WARNING  | utils.my_handle:comment_handle:2811 - 使用流式推理LLM
2024-08-23 23:13:22.826 | ERROR    | utils.my_handle:llm_stream_handle_and_audio_synthesis:1773 - Traceback (most recent call last):
  File "E:\AIVtuber\utils\my_handle.py", line 1640, in llm_stream_handle_and_audio_synthesis
    tmp += chunk.choices[0].delta.content
TypeError: can only concatenate str (not "NoneType") to str

2024-08-23 23:13:28.312 | INFO     | utils.audio:my_play_voice:1273 - edge-tts合成成功，合成内容：【主人说:你好】，输出 到=E:\AIVtuber\out\edge_tts_6.mp3
2024-08-23 23:13:28.317 | INFO     | utils.audio:data_priority_insert:573 - 待播放音频列表 优先级: 20 音频=E:\AIVtuber\out\edge_tts_6.mp3
2024-08-23 23:13:30.965 | INFO     | __main__:callback:228 - API收到数据：{'type': 'audio_playback_completed', 'data': {'wait_play_audio_num': 0, 'wait_synthesis_msg_num': 0}}
INFO:     127.0.0.1:59445 - "POST /callback HTTP/1.1" 200 OK

### 复现步骤

1.正常下载解压
2.双击启动
3.填写api验证正常
4.聊天界面进行对话

### 期望的结果

大语言模型应该能正常得出结果

### 截图或日志

![image](https://github.com/user-attachments/assets/828d3697-9912-4b33-bedc-243520031f8c)
![image](https://github.com/user-attachments/assets/412d41be-1d02-48ed-8c0e-957dcca3f99d)

**Comment by Ikaros-521** [comment]
> ### 操作系统
> Windows
> 
> ### Python 版本
> 3.10.11
> 
> ### AI Vtuber 版本
> 20240823
> 
> ### 描述问题
> 我使用的是SiliconCloud的api，验证是通过的，在其他版本（0723）上也是可以在聊天页面中正常出现语音对话，但是在0823版本中却不行了，关键部分错误如下： 2024-08-23 23:13:21.829 | WARNING | utils.my_handle:comment_handle:2811 - 使用流式推理LLM 2024-08-23 23:13:22.826 | ERROR | utils.my_handle:llm_stream_handle_and_audio_synthesis:1773 - Traceback (most recent call last): File "E:\AIVtuber\utils\my_handle.py", line 1640, in llm_stream_handle_and_audio_synthesis tmp += chunk.choices[0].delta.content TypeError: can only concatenate str (not "NoneType") to str
> 
> 2024-08-23 23:13:28.312 | INFO | utils.audio:my_play_voice:1273 - edge-tts合成成功，合成内容：【主人说:你好】，输出 到=E:\AIVtuber\out\edge_tts_6.mp3 2024-08-23 23:13:28.317 | INFO | utils.audio:data_priority_insert:573 - 待播放音频列表 优先级: 20 音频=E:\AIVtuber\out\edge_tts_6.mp3 2024-08-23 23:13:30.965 | INFO | **main**:callback:228 - API收到数据：{'type': 'audio_playback_completed', 'data': {'wait_play_audio_num': 0, 'wait_synthesis_msg_num': 0}} INFO: 127.0.0.1:59445 - "POST /callback HTTP/1.1" 200 OK
> 
> ### 复现步骤
> 1.正常下载解压 2.双击启动 3.填写api验证正常 4.聊天界面进行对话
> 
> ### 期望的结果
> 大语言模型应该能正常得出结果
> 
> ### 截图或日志
> ![image](https://private-user-images.githubusercontent.com/32669380/360978892-828d3697-9912-4b33-bedc-243520031f8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDkxOTksIm5iZiI6MTcyNDY0ODg5OSwicGF0aCI6Ii8zMjY2OTM4MC8zNjA5Nzg4OTItODI4ZDM2OTctOTkxMi00YjMzLWJlZGMtMjQzNTIwMDMxZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA1MDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjVkOTcyNWJiMTFlMmI0Yzk3YWY4OTVmNDViOTI2NzU2M2NhMzY0ZTJjZjY5MGM0NzE4MGYwMzlhY2VhZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FFDmVJqkDrqbLGke9xKIqrL7nX0VLIkVSntik1wWoMA) ![image](https://private-user-images.githubusercontent.com/32669380/360979144-412d41be-1d02-48ed-8c0e-957dcca3f99d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDkxOTksIm5iZiI6MTcyNDY0ODg5OSwicGF0aCI6Ii8zMjY2OTM4MC8zNjA5NzkxNDQtNDEyZDQxYmUtMWQwMi00OGVkLThjMGUtOTU3ZGNjYTNmOTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA1MDgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NzJlYjA0Zjg1YWY1OTMxMGVlMjJmZjBjZGEzZWNiMWNiNGI2NjM5Mzc5OGQzNzc2MmIzYmNkZDZkMGMxZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bYJslPFYm6MVpTzdrRB7VBebGxO603TTlL1gm9zRDMw)

关闭流式输出

**Comment by Ikaros-521** [comment]
新版本已经对 测试检验做了加强逻辑，测试不通过时可以看到详细错误信息，

**Comment by geekane** [comment]
> 流式确实不兼容，关了就行了
好的感谢讲解
