### ISSUE TITLE
在Huggingface上有一個有趣的模型，希望能使用在這個項目裡

### ISSUE THREAD

**Issue by albertyu123456789** [Ikaros-521/AI-Vtuber#988]
### 希望能解决的问题
[https://huggingface.co/gpt-omni/mini-omni](https://huggingface.co/gpt-omni/mini-omni)

### 描述所需要的功能

希望能夠在這個項目裡使用到

**Comment by Ikaros-521** [comment]
等人出整合包后，看看  计划中
