### ISSUE TITLE
🚀 Feature: 功能描述：CosyVoice-win-0819更新

### ISSUE THREAD

**Issue by huangse199** [Ikaros-521/AI-Vtuber#994]
### 希望能解决的问题

目前CosyVoice已经更新到0819版本，b站刘悦佬的整合包多了许多新功能，例如自然语言控制情绪，可以通过训练微调模型让模型在输出文本时表达情绪关键词，通过CosyVoice的api调用合成真实的语音

### 描述所需要的功能

我不到啊，佬有时间看看就行

**Comment by Ikaros-521** [comment]
https://github.com/Ikaros-521/AI-Vtuber/pull/996
